#!/bin/sh

usage() {
    echo "Usage: $0 <os-platform>"
    exit 1
}

if [ $# -ne 1 ]
then
    usage $*
fi

cd myRtspClient
/bin/rm -f Makefile
cat Makefile.head ../config.$1 Makefile.tail > Makefile
chmod a-w Makefile

cd ../example
/bin/rm -f Makefile
cat Makefile.head ../config.$1 Makefile.tail > Makefile
chmod a-w Makefile

cd ../third_party/Base64_live555
/bin/rm -f Makefile
cat Makefile.head ../../config.$1 Makefile.tail > Makefile
chmod a-w Makefile

cd ../../third_party/jrtplib-3.9.1
/bin/rm -f Makefile
cat Makefile.head ../../config.$1 Makefile.tail > Makefile
chmod a-w Makefile

cd ../../
/bin/rm -f Makefile
cat Makefile.head config.$1 Makefile.tail > Makefile
chmod a-w Makefile
